### ISSUE TITLE
err after upd to 1.1.0

### ISSUE THREAD

**Issue by blondie63** [lohanidamodar/flutter_custom_clippers#10]
Hi, after update to last v1.1.0 i've this error:
The argument type 'OvalTopBorderClipper' can't be assigned to the parameter type 'CustomClipper<Rect>'.

How can i fix it ?
Thanks

**Comment by lohanidamodar** [comment]
Please post the code you are using OvalTopBorderClipper with.

**Comment by blondie63** [comment]
`  Widget _buildTotals() {
    return ClipOval(
      clipper: OvalTopBorderClipper(),
      child: Container(
        height: 180,
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(blurRadius: 5.0,color: Colors.grey.shade700,spreadRadius: 80.0),
          ],
          color: Colors.white,
        ),
        padding: EdgeInsets.only(left: 20.0, right: 20.0, top: 40.0, bottom: 10.0),
        child: Column(
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text("Subtotal"),
                Text("Rs. 1500"),
              ],
            ),
            SizedBox(height: 10.0,),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text("Delivery fee"),
                Text("Rs. 100"),
              ],
            ),
            SizedBox(height: 10.0,),  
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text("Total"),
                Text("Rs. 1600"),
              ],
            ),
            SizedBox(height: 10.0,),
            RaisedButton(
              color: Colors.green,
              onPressed: (){},
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: <Widget>[
                  Text("Continue to Checkout", style: TextStyle(color: Colors.white)),
                  Text("Rs. 1600", style: TextStyle(color: Colors.white)),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }`

This code is part of your prj https://github.com/lohanidamodar/flutter_ui_challenges :)

**Comment by lohanidamodar** [comment]
I think in my ui challenge i am using different oval top clipper, for this to work just change the ClipOval to ClipPath as the OvalTopBorderClipper in this package uses Path instead of Rect
