### ISSUE TITLE
Animating?

### ISSUE THREAD

**Issue by klaszlo8207** [lohanidamodar/flutter_custom_clippers#11]
Is there any way to animating the clipped values?

**Comment by lohanidamodar** [comment]
Of course, It is possible to animate the clipper values by passing the value from animation controller to the clipper.

Checkout this library https://github.com/aagarwal1012/IntroViews-Flutter they have used a circular clipper and animated revealing page or checkout this vignettes from flutter interact, where they use gooey edge clipper to animate page reveal https://github.com/gskinnerTeam/flutter_vignettes/tree/master/vignettes/gooey_edge
