### ISSUE TITLE
How do I add a shadow?

### ISSUE THREAD

**Issue by GanZhiXiong** [lohanidamodar/flutter_custom_clippers#12]

**Comment by isaacpitwa** [comment]
Any solution to this ???

**Comment by lohanidamodar** [comment]
Please checkout [this example](https://gist.github.com/coman3/e631fd55cd9cdf9bd4efe8ecfdbb85a7) or [this package](https://gist.github.com/coman3/e631fd55cd9cdf9bd4efe8ecfdbb85a7).
Those might be what you are looking for.
