### ISSUE TITLE
How to make a curved bottom app bar

### ISSUE THREAD

**Issue by TahaMalas** [lohanidamodar/flutter_custom_clippers#13]
Hi!, I'm trying to implement this screenshot with bottom app bar, I didn't manage to make the SideCutClipper to be at the top of the bottom app bar any ideas?

![Image description](https://i.ibb.co/vxSSbMk/my-kia.png)

**Comment by lohanidamodar** [comment]
For that you don't need custom clippers, just use `ClipRRect` for example
```
ClipRRect(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(20.0),
          topRight: Radius.circular(20.0)
        ),
              child: BottomAppBar(
          shape: CircularNotchedRectangle(),
          child: Container(
            height: kToolbarHeight,
          ),

        ),
      )
```

**Comment by TahaMalas** [comment]
> For that you don't need custom clippers, just use `ClipRRect` for example
> 
> ```
> ClipRRect(
>         borderRadius: BorderRadius.only(
>           topLeft: Radius.circular(20.0),
>           topRight: Radius.circular(20.0)
>         ),
>               child: BottomAppBar(
>           shape: CircularNotchedRectangle(),
>           child: Container(
>             height: kToolbarHeight,
>           ),
> 
>         ),
>       )
> ```

The solution you're suggesting is only for the curved top right and top left corners right? I'm asking for the curve on the selected tab in the bottom tab bar.

**Comment by lohanidamodar** [comment]
I think this is what you are looking for then,
https://github.com/rafalbednarczuk/curved_navigation_bar

**Comment by TahaMalas** [comment]
> I think this is what you are looking for then,
> https://github.com/rafalbednarczuk/curved_navigation_bar

Exactly, thank you so much, and sorry for the inconvenience

**Comment by lohanidamodar** [comment]
No problem! Glad to help!
