### ISSUE TITLE
Request for inverted WaveClipperOne && WaveClipperTwo

### ISSUE THREAD

**Issue by Alijaaan** [lohanidamodar/flutter_custom_clippers#14]
Hi,

Great and beautiful clippers.
It would be great if you add inverted option to the class or add WaveClipperOneInverted and WaveClipperTwoInverted in this class.

Thanks in advance

**Comment by lohanidamodar** [comment]
Try `WaveClipperOne(reverse: true)` or `WaveClipperTwo(reverse: true)`

**Comment by Alijaaan** [comment]
many thanks for your prompt reply,
reverse is just invert the clipper vertically , i need to invert it horizontally.

**Comment by lohanidamodar** [comment]
Can you please provide the sample, Thank you.

**Comment by Alijaaan** [comment]
I tried to upload pictures here but it seems something went wrong.Let me find a solution to show

**Comment by Alijaaan** [comment]
Main :
https://pasteboard.co/J4o4aaW.jpg

Inverted Horizontally:
https://pasteboard.co/J4o59JQ.jpg

**Comment by Alijaaan** [comment]
> Main :
> https://pasteboard.co/J4o4aaW.jpg
> 
> Inverted Horizontally:
> https://pasteboard.co/J4o59JQ.jpg

Is there any solution?

**Comment by lohanidamodar** [comment]
You will have the solution soon.

**Comment by lohanidamodar** [comment]
Checkout `WaveClipperOne(flip: true)` and `WaveClipperTwo(flip: true)` on latest version `v1.1.1`

**Comment by Alijaaan** [comment]
> Checkout `WaveClipperOne(flip: true)` and `WaveClipperTwo(flip: true)` on latest version `v1.1.1`

Dear lohanidamodar,
Many thanks for great suport.
It's exactly what I was looking for.
But it seems it has a little problem.
Please take a look at images:

Source:
https://pasteboard.co/J5qHhCa.jpg

Flipe:
https://pasteboard.co/J5qHCl5.jpg
