### ISSUE TITLE
notification received when app crashes in flutter

### ISSUE THREAD

**Issue by choudhryr723** [lohanidamodar/flutter_custom_clippers#16]
error
D/AndroidRuntime(24012): Shutting down VM
E/AndroidRuntime(24012): FATAL EXCEPTION: main
E/AndroidRuntime(24012): Process: com.rayz.arrow, PID: 24012
E/AndroidRuntime(24012): java.lang.RuntimeException: Unable to instantiate service com.rayz.arrow.Application: java.lang.ClassCastException: com.rayz.arrow.Application cannot be cast to android.app.Service
E/AndroidRuntime(24012): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3940)
E/AndroidRuntime(24012): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime(24012): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime(24012): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(24012): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24012): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(24012): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24012): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(24012): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(24012): Caused by: java.lang.ClassCastException: com.rayz.arrow.Application cannot be cast to android.app.Service
E/AndroidRuntime(24012): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(24012): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(24012): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3935)
E/AndroidRuntime(24012): 	... 8 more
I/Process (24012): Sending signal. PID: 24012 SIG: 9

**Comment by choudhryr723** [comment]
help me

**Comment by lohanidamodar** [comment]
Closing this issue, as this is not related to the package. Please try on stackoverflow with the code that caused the problem
