### ISSUE TITLE
design instagram message shape

### ISSUE THREAD

**Issue by pishguy** [lohanidamodar/flutter_custom_clippers#2]
how can we design this shape in flutter?

![instagram shape message](https://user-images.githubusercontent.com/6617583/60760879-e7026600-a051-11e9-9343-c8d19ce36816.jpg)

thanks

**Comment by lohanidamodar** [comment]
@cimplesid do you want to implement this?

**Comment by cimplesid** [comment]
i will try for sure

**Comment by cimplesid** [comment]
> @cimplesid do you want to implement this?

check pr

**Comment by lohanidamodar** [comment]
Solved by #3

**Comment by pishguy** [comment]
@lohanidamodar @cimplesid 

there are some wrong points and lines


![message](https://user-images.githubusercontent.com/6617583/60766072-53648000-a0b9-11e9-909f-fef06f3d9897.png)

**Comment by cimplesid** [comment]
> @lohanidamodar @cimplesid
> 
> there are some wrong points and lines
> 
> ![message](https://user-images.githubusercontent.com/6617583/60766072-53648000-a0b9-11e9-909f-fef06f3d9897.png)

it is a solution but not an optimal you can use this for now if any improvement  are made i will mention you  here . just update the package later it will be ok

**Comment by lohanidamodar** [comment]
@MahdiPishguy  @cimplesid  
checkout version 1.0.4, it should solve this problem!

**Comment by pishguy** [comment]
@lohanidamodar thanks a lot
