### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by leynier** [lohanidamodar/flutter_custom_clippers#20]
I will make a PR with null safety support implementation

**Comment by yusriltakeuchi** [comment]
great job bro @leynier , i'm waiting also

**Comment by anchal-td** [comment]
is this migrated to null safety ? Can anyone provide version number or github link with null safety support ?

**Comment by astudilloalex** [comment]
The Null Support is required, please

**Comment by rahulrkhot** [comment]
Null Safety Support Required

**Comment by ghozay19** [comment]
any update ?
